2020-02-05 13:15:25,900 (8401/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-02-05 13:15:25,900 (8401/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-02-05 22:53:18,879 (24308/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-02-05 22:53:18,879 (24308/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-02-05 23:43:11,178 (24308/MainThread) pgcli.pgexecute ERROR - sql: '\\d medications', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-05 23:43:11,185 (24308/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 402, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgspecial/dbcommands.py", line 711, in describe_table_details\n    cur.execute(sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-05 23:43:11,185 (24308/MainThread) pgcli.main ERROR - sql: '\\d medications', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-05 23:43:11,187 (24308/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 402, in run\n    for result in pgspecial.execute(cur, sql):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgspecial/main.py", line 90, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgspecial/dbcommands.py", line 711, in describe_table_details\n    cur.execute(sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-05 23:43:26,581 (24308/MainThread) pgcli.pgexecute ERROR - sql: 'drop tables iz_searches', error: SyntaxError('syntax error at or near "tables"\nLINE 1: drop tables iz_searches\n             ^\n')
2020-02-05 23:43:26,582 (24308/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "tables"\nLINE 1: drop tables iz_searches\n             ^\n\n'
2020-02-05 23:44:05,825 (24308/MainThread) pgcli.pgexecute ERROR - sql: 'delete from schema_migrations where version = 20200204192837', error: UndefinedFunction('operator does not exist: character varying = bigint\nLINE 1: delete from schema_migrations where version = 20200204192837\n                                                    ^\nHINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.\n')
2020-02-05 23:44:05,826 (24308/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedFunction: operator does not exist: character varying = bigint\nLINE 1: delete from schema_migrations where version = 20200204192837\n                                                    ^\nHINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.\n\n'
2020-02-06 01:48:12,935 (24308/MainThread) pgcli.pgexecute ERROR - sql: 'select * from schema_migrations', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-06 01:48:12,935 (24308/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-06 01:48:12,935 (24308/MainThread) pgcli.main ERROR - sql: 'select * from schema_migrations;', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-06 01:48:12,935 (24308/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-06 01:51:31,212 (24308/MainThread) pgcli.pgexecute ERROR - sql: 'drop table iz_histories', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-06 01:51:31,212 (24308/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-06 01:51:31,212 (24308/MainThread) pgcli.main ERROR - sql: 'drop table iz_histories;', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-06 01:51:31,212 (24308/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-10 00:02:33,055 (16379/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-02-10 00:02:33,056 (16379/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-02-10 00:52:19,193 (16379/MainThread) pgcli.pgexecute ERROR - sql: 'A', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-10 00:52:19,195 (16379/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-10 00:52:19,195 (16379/MainThread) pgcli.main ERROR - sql: 'A', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-10 00:52:19,196 (16379/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-10 00:52:19,202 (16379/MainThread) pgcli.pgexecute ERROR - sql: 'A', error: SyntaxError('syntax error at or near "A"\nLINE 1: A\n        ^\n')
2020-02-10 00:52:19,203 (16379/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "A"\nLINE 1: A\n        ^\n\n'
2020-02-10 15:17:09,660 (3443/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-02-10 15:17:09,661 (3443/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-02-10 15:18:43,354 (3443/MainThread) pgcli.pgexecute ERROR - sql: 'drop table iz_searches', error: DependentObjectsStillExist('cannot drop table iz_searches because other objects depend on it\nDETAIL:  constraint fk_rails_23db20bc5d on table iz_histories depends on table iz_searches\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n')
2020-02-10 15:18:43,355 (3443/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.DependentObjectsStillExist: cannot drop table iz_searches because other objects depend on it\nDETAIL:  constraint fk_rails_23db20bc5d on table iz_histories depends on table iz_searches\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n\n'
2020-02-10 15:20:59,743 (3443/MainThread) pgcli.pgexecute ERROR - sql: 'select * from iz_searches', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-10 15:20:59,744 (3443/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-10 15:20:59,744 (3443/MainThread) pgcli.main ERROR - sql: 'select * from iz_searches', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-10 15:20:59,745 (3443/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-10 15:22:19,884 (3443/MainThread) pgcli.pgexecute ERROR - sql: 'delete * from iz_searches', error: SyntaxError('syntax error at or near "*"\nLINE 1: delete * from iz_searches\n               ^\n')
2020-02-10 15:22:19,884 (3443/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "*"\nLINE 1: delete * from iz_searches\n               ^\n\n'
2020-02-10 15:39:35,099 (3443/MainThread) pgcli.pgexecute ERROR - sql: 'delete  from iz_histories', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-10 15:39:35,100 (3443/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-10 15:39:35,100 (3443/MainThread) pgcli.main ERROR - sql: 'delete  from iz_histories', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-10 15:39:35,100 (3443/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-10 16:25:37,868 (3443/MainThread) pgcli.pgexecute ERROR - sql: 'delete  from iz_histories', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-10 16:25:37,869 (3443/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-10 16:25:37,869 (3443/MainThread) pgcli.main ERROR - sql: 'delete  from iz_histories', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n')
2020-02-10 16:25:37,869 (3443/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2020-02-10 16:25:41,365 (3443/MainThread) pgcli.main ERROR - sql: 'delete  from iz_histories', error: InterfaceError('connection already closed')
2020-02-10 16:25:41,366 (3443/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 447, in execute_normal_sql\n    cur = self.conn.cursor()\npsycopg2.InterfaceError: connection already closed\n'
2020-02-10 16:31:53,711 (3443/MainThread) pgcli.main ERROR - sql: 'delete  from iz_histories', error: InterfaceError('connection already closed')
2020-02-10 16:31:53,712 (3443/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 447, in execute_normal_sql\n    cur = self.conn.cursor()\npsycopg2.InterfaceError: connection already closed\n'
2020-02-10 16:49:38,147 (3443/MainThread) pgcli.main ERROR - sql: 'delete  from iz_searches;', error: InterfaceError('connection already closed')
2020-02-10 16:49:38,148 (3443/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 447, in execute_normal_sql\n    cur = self.conn.cursor()\npsycopg2.InterfaceError: connection already closed\n'
2020-02-10 16:49:43,039 (3443/MainThread) pgcli.main ERROR - sql: 'delete  from iz_searches;', error: InterfaceError('connection already closed')
2020-02-10 16:49:43,039 (3443/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 447, in execute_normal_sql\n    cur = self.conn.cursor()\npsycopg2.InterfaceError: connection already closed\n'
2020-02-10 16:49:45,226 (3443/MainThread) pgcli.main ERROR - sql: 'select * from iz_searches', error: InterfaceError('connection already closed')
2020-02-10 16:49:45,226 (3443/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 638, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/main.py", line 883, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 447, in execute_normal_sql\n    cur = self.conn.cursor()\npsycopg2.InterfaceError: connection already closed\n'
2020-02-10 16:49:47,980 (18336/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-02-10 16:49:47,980 (18336/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-02-10 16:49:57,746 (18336/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2020-02-10 16:49:57,746 (18336/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2020-02-10 16:50:03,123 (18336/MainThread) pgcli.pgexecute ERROR - sql: 'delete  from iz_searches', error: ForeignKeyViolation('update or delete on table "iz_searches" violates foreign key constraint "fk_rails_23db20bc5d" on table "iz_histories"\nDETAIL:  Key (id)=(2) is still referenced from table "iz_histories".\n')
2020-02-10 16:50:03,123 (18336/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 413, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/jefflangston/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 448, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.ForeignKeyViolation: update or delete on table "iz_searches" violates foreign key constraint "fk_rails_23db20bc5d" on table "iz_histories"\nDETAIL:  Key (id)=(2) is still referenced from table "iz_histories".\n\n'
